"""
Game constants for Zatikon.
"""

# Board configuration
BOARD_SIZE = 11
MAX_COMMANDS = 5

# Teams
TEAM_NONE = 0
TEAM_1 = 1
TEAM_2 = 2

# Action types
ACTION_ATTACK = 0
ACTION_MOVE = 1
ACTION_SPELL = 2
ACTION_SKILL = 3
ACTION_OTHER = 4
ACTION_DEPLOY = 37
ACTION_END_TURN = 38

# Target types
TARGET_ANY_LINE = 0
TARGET_ANY_LINE_JUMP = 1
TARGET_ANY_AREA = 2
TARGET_LOCATION_LINE = 3
TARGET_LOCATION_LINE_JUMP = 4
TARGET_LOCATION_AREA = 5
TARGET_UNIT_LINE = 6
TARGET_UNIT_LINE_JUMP = 7
TARGET_UNIT_AREA = 8
TARGET_NONE = 9
TARGET_CASTLE = 10

# Selection types
SELECTION_FRIENDLY = 0
SELECTION_ENEMY = 1
SELECTION_BOTH = 2
SELECTION_MOVE = 3

# Attack types
ATTACK_ARROW = 0
ATTACK_MELEE = 1
ATTACK_OTHER = 2
ATTACK_CHANNEL_BOLT = 3
ATTACK_CHANNEL_BLAST = 4
ATTACK_STONE = 5
ATTACK_SPEAR = 6
ATTACK_MAGIC_BALL = 7
ATTACK_XBOW = 8
ATTACK_WISP = 9
ATTACK_BLOWGUN = 10
ATTACK_SPIRIT = 11
ATTACK_BEAM = 12
ATTACK_NONE = 13
ATTACK_THROW = 14
ATTACK_THROW_SPEAR = 15
ATTACK_RELIC = 16

# Event types
EVENT_PREVIEW_ACTION = 0
EVENT_WITNESS_ACTION = 1
EVENT_PREVIEW_MOVE = 2
EVENT_WITNESS_MOVE = 3
EVENT_PREVIEW_DAMAGE = 4
EVENT_WITNESS_DAMAGE = 5
EVENT_PREVIEW_DEATH = 6
EVENT_WITNESS_DEATH = 7
EVENT_COUNT = 8

# Event results
EVENT_PARRY = -3
EVENT_NONE = -4
EVENT_CANCEL = -5
EVENT_OK = -6
EVENT_TRUE = -7
EVENT_FALSE = -8
EVENT_DEAD = -9
EVENT_END = -10

# Unit IDs (matching UnitType enum)
UNIT_FOOTMAN = 0
UNIT_BOWMAN = 1
UNIT_CAVALRY = 2
UNIT_ARCHER = 3
UNIT_PIKEMAN = 4
UNIT_KNIGHT = 5
UNIT_RANGER = 6
UNIT_WOLF = 7
UNIT_SUMMONER = 8
UNIT_BEAR = -8
UNIT_PRIEST = 11
UNIT_ENCHANTER = 12
UNIT_TEMPLAR = 13
UNIT_WARRIOR = 14
UNIT_RIDER = 15
UNIT_HEALER = 16
UNIT_WIZARD = 17
UNIT_SCOUT = 18
UNIT_ASSASSIN = 19
UNIT_TACTICIAN = 20
UNIT_GENERAL = 21
UNIT_WALL = 22
UNIT_MASON = 23
UNIT_CATAPULT = 24
UNIT_BALLISTA = 25
UNIT_NECROMANCER = 26
UNIT_LICH = 27
UNIT_SERGEANT = 30
UNIT_ABJURER = 31
UNIT_SEAL = 32
UNIT_WARLOCK = 33
UNIT_CROSSBOWMAN = 34
UNIT_DRAGON = 35
UNIT_DRACOLICH = 36
UNIT_HYDRA = 37
UNIT_TOWER = 38
UNIT_COMMAND_POST = 39
UNIT_BARRACKS = 40
UNIT_DRUID = 42
UNIT_CHANNELER = 43
UNIT_LYCANTHROPE = 44
UNIT_WEREWOLF = 45
UNIT_LYCANWOLF = 46
UNIT_MOUNTED_ARCHER = 47
UNIT_GEOMANCER = 48
UNIT_ROCK = 49
UNIT_SWORDSMAN = 50
UNIT_WITCH = 51
UNIT_TOAD = 52
UNIT_SHIELD_MAIDEN = 53
UNIT_MAGUS = 54
UNIT_SPIRIT = 55
UNIT_GOLEM = 57
UNIT_ARMORY = 58
UNIT_FIRE_ARCHER = 60
UNIT_MIMIC = 61
UNIT_PALADIN = 62
UNIT_SHAMAN = 63
UNIT_MARTYR = 64
UNIT_ROGUE = 65
UNIT_DIABOLIST = 66
UNIT_GHOST = 67
UNIT_GATE_GUARD = 68
UNIT_FEATHERED_SERPENT = 69
UNIT_BERSERKER = 70
UNIT_ARTIFICER = 71
UNIT_CHANGELING = 72
UNIT_DOPPELGANGER = 73
UNIT_SKINWALKER = 74
UNIT_ACOLYTE = 75
UNIT_NONE = 123

